### ISSUE TITLE
Add following Search functions

### ISSUE THREAD

**Issue by bsssp** [scherenhaenden/Angular-GeneralPackageManager#2]
1) Show only searched packages
2) Trigger the Search by pressing Enter
3) Show the Info and the version of the selected package on the result list

**Comment by scherenhaenden** [comment]
Please! remember no to create a bunch of issues in a ticket.
- Show only searched packages: there is not local filter for searching because the packages are on public servers. How ever the packages get loaded now from Nuget.

-Trigger the Search by pressing Enter: Great thing, i had forgotten that one! thanks! i merged that one yesterday.

-Show the Info and the version of the selected package on the result list: like the other things is this one a feature not an issue. I merged the code u sent yesterday. The state of the project is not yet to show this information. This is because there is research to be done. Im on other funcionts. 

Thanks!
